<?xml version ="1.0" encoding="UTF-8"?>
<!DOCTYPE catalog [
<!ELEMENT catalog (articol*)>
<!ELEMENT articol (nume, categorie)>
<!ELEMENT nume (#PCDATA)>
<!ELEMENT categorie (#PCDATA)>
<!ATTLIST articol id CDATA #REQUIRED>
]>
<catalog>
<articol id='1'>
    <nume>PepsiCola</nume>
    <categorie>Bauturi</categorie>
</articol>
<articol id='2'>
    <nume>Televizor</nume>
    <categorie>Electronice</categorie>
</articol>
<articol id='3'>
    <nume>Aspirator</nume>
    <categorie>Electrocasnice</categorie>
</articol>
</catalog>




